name: Run Discord Bot

on:
  push:
    branches:
      - main  # This will trigger the workflow when you push to the main branch
  workflow_dispatch:  # Allows you to manually trigger the workflow from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # This is the environment where the bot will run (Ubuntu Linux)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This step checks out your repository code so the workflow can use it

    - name: Set up Python
      uses: actions/setup-python@v2  # This sets up the Python environment
      with:
        python-version: '3.x'  # Install the latest version of Python 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip (Python's package manager)
        pip install -r requirements.txt  # Install the dependencies listed in requirements.txt

    - name: Run bot
      run: |
        python bot.py  # Replace bot.py with the name of your bot script
